# Generated by Django 3.2.11 on 2022-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_meals_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='meal_status',
            field=models.CharField(choices=[('CP', 'Complete'), ('CC', 'Cancelled'), ('DL', 'Delivered')], max_length=200),
        ),
    ]
