# Generated by Django 3.2.12 on 2022-03-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220330_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='meal_category',
        ),
        migrations.DeleteModel(
            name='MealCategory',
        ),
    ]
