# Generated by Django 3.2.12 on 2022-03-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220331_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='meal_category',
        ),
        migrations.AlterField(
            model_name='meals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
