# Generated by Django 3.2.12 on 2022-03-31 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220331_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='meal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mealcategory'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
