# Generated by Django 3.2.13 on 2022-05-24 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220331_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='meal_status',
            field=models.CharField(choices=[('CP', 'Complete'), ('CC', 'Cancelled'), ('DL', 'Delivered')], default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meals',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
