# Generated by Django 3.2.13 on 2022-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220524_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
