# Generated by Django 3.2.13 on 2022-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_meals_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
